# Generated by Django 5.0.6 on 2024-06-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0002_cliente_foto_perfil_cliente_genero_cliente_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
