# Generated by Django 5.0.6 on 2024-06-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0003_endereco_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
